# Generated by Django 5.0.7 on 2024-12-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0002_product_vehiclereport_websitecontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
