# Generated by Django 4.2 on 2024-12-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0004_newsletters_delete_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletters',
            new_name='Register',
        ),
    ]
