# Generated by Django 4.2 on 2024-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0006_rename_created_at_vehiclereport_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
