# Generated by Django 5.0.7 on 2024-12-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0007_createform_loginforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vehicle_image', models.ImageField(upload_to='images/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclereport',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='vehicle_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
