# Generated by Django 5.0.7 on 2024-12-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0008_imagemodel_vehiclereport_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereport',
            name='vehicle_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
