# Generated by Django 5.0.7 on 2024-12-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0009_alter_vehiclereport_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclereport',
            name='date',
        ),
    ]
