# Generated by Django 5.0.7 on 2024-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0010_remove_vehiclereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
