# Generated by Django 5.0.7 on 2024-12-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0012_alter_register_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(default='YYYY-MM-DD'),
        ),
    ]
