# Generated by Django 5.0.7 on 2024-12-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0013_alter_register_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclereport',
            name='datetime',
            field=models.DateTimeField(default='YYYY-MM-DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(default='YYYY-MM-DD HH:MM:SS'),
        ),
    ]
