# Generated by Django 5.0.7 on 2024-12-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0014_vehiclereport_datetime_alter_register_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
    ]
