# Generated by Django 5.0.7 on 2024-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0016_alter_register_datetime_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
