# Generated by Django 5.0.7 on 2024-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0017_alter_register_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
