# Generated by Django 5.0.7 on 2024-12-10 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0019_alter_vehiclereport_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
        migrations.AlterField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
